name: Artifact
on:  
  workflow_dispatch:
    inputs: 
      word:
        type: choice
        options:
          - yes
          - no
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: date > data.txt
      - uses: actions/upload-artifact@v4
        with:
          name: upload
          path: data.txt
          retention-days: 7
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: upload
          path: downloaded
      - run: cat downloaded/data.txt
  
