name: Enviromento variables
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A Cheerful word
jobs:
  runs:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        ref: ${{env.BRANCH}}  
